name: Counter Deploy Test
run-name: ${{ github.actor }} is testing the counter service
on: 
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  Build-Deb-Pkg:
    runs-on: [self-hosted, linux, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install make
        run:  apt-get update && apt-get install make
      - name: Build Debian package
        run: |
          echo "Building debian package..."
          make build-deb
      - name: Saving package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-pkg
          path: counter-v2.0.0.deb
      - name: Copying debian pkg to VM 
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "counter-v2.0.0.deb"
          target: ./
      - name: Updating package with new version
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          passphrase: ""
          script:  sudo dpkg -i counter-v2.0.0.deb
      - run: echo "This job's status is ${{ job.status }}." 